<VirtualHost *:80>
#Basic
	ServerAdmin admin@DOMAIN_NAME
	ServerName DOMAIN_NAME
	DocumentRoot BASE_DIR/DIR_NAME/www/

#Log
	ErrorLog BASE_DIR/DIR_NAME/logs/error.log
	LogLevel warn
	CustomLog BASE_DIR/DIR_NAME/logs/access.log combined

# Virtual Directories and Others
	Include BASE_DIR/DIR_NAME/conf/httpd.conf.d/wsgi.def
	Include BASE_DIR/DIR_NAME/conf/httpd.conf.d/*.conf

</VirtualHost>
